---
title: "StickleImputationCode"
author: "Akhil Ghosh"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mice)
```

```{r}
#setwd('/Users/akhilghosh/Desktop/RStudioProjects2022Fall/SticklebackProject/RawData_ReadOnly')
stickle <- read_csv("../RawData_ReadOnly/AO.sexualdimorphismPruned.sc.forAnalysis_forMICE_Modeling_20June2023.csv")

summary(stickle)
stick <- stickle %>% 
  mutate(gender = as.factor(case_when(
    grepl(".M.",univID,fixed=TRUE) ~ "Male",
    grepl(".F.",univID,fixed=TRUE) ~ "Female",
    grepl("Fos",univID,fixed=TRUE) ~ NA_character_
    ))
  ) %>% 
  select(gender, everything())

#Manual Fixes
 # <!-- LQx.B.M.139 was called male in hand (and in our database) but is female by dissection. -->
 # <!-- LQx.B.M.155 was called male in hand (and in our database) but is female by dissection. -->
 # <!--     Pax.B.M.081 was called male in hand (and in our database) but is female by dissection. -->
 # <!--     Pax.L.M.113 was called male in hand (and in our database) but is female by dissection. -->
 # <!--     Pax.L.M.115 was called male in hand (and in our database) but is female by dissection. -->
stick$gender[stick$univID == "LQx.B.M.139"] <- "Female"
#stick$gender[stick$univID == "LQx.B.M.155"] <- "Female"
stick$gender[stick$univID == "Pax.B.M.081"] <- "Female"
stick$gender[stick$univID == "Pax.L.M.113"]<- "Female"
stick$gender[stick$univID == "Pax.L.M.115"] <- "Female"
```

```{r}
set.seed(0314)
imputations = 100
stick_whole <- stick %>% select(-c(univID))
summary(stick_whole)
imputed_stick_whole <- mice(stick_whole,m=imputations)
complete_stick_list <- list()
for(m in 1:imputations){
  complete_stick_list[[m]] <- complete(imputed_stick_whole, m)
}
```


```{r}
univ <- stick %>% 
  mutate(time = as.integer(sub(".*([0-9]{2})\\..*", "\\1",univID)))
times <- univ %>% drop_na(time) %>% pull(time)

times_vector <- c(rep(1,43)) %>% 
  append(21-times)
```


```{r}
csv_list <-list()
for(i in 1:imputations){
csv_list[[i]] <- complete_stick_list[[i]][-c(1:367),] %>% mutate(imp = rep(i, 814), time = times_vector)
}

combined_csv<- do.call(rbind,csv_list) %>% select(imp, time,gender, everything())
write_csv(combined_csv, file = "../Data/updated_stickle_imputations_100_20250904.csv")
```


```{r}
combined_csv <- read.csv("../Data/updated_stickle_imputations_100_20250904.csv")
combined_csv %>% group_by(imp) %>% summarize(percent_male = 100*mean(gender == "Male")) %>% ggplot(aes(x = percent_male)) + geom_density() + theme_bw() + xlab("Percent Male")
```





# Cross validation

```{r}
set.seed(2025)
stick_extant <- stick %>% filter(substring(univID,1,3) != "Fos") 
stick_extant$ind <- sample(rep(1:5,75), nrow(stick_extant),replace = FALSE)


M <- 100
preds <- list()
for (i in 1:5){
temp <- stick_extant 
temp$gender[temp$ind == i] <- NA
imp_temp <- mice(temp %>% select(-ind),m = M)
comp_temp <- complete(imp_temp, "long")
comp_temp$ind <- rep(temp$ind,M)
comp_temp <- comp_temp %>% mutate(gender_true = rep(stick_extant$gender,M)) %>% filter(ind == i) 
preds[[i]] <- comp_temp %>% group_by(.id, gender_true) %>% summarize(pct_male = mean(gender == "Male"))
}

stack <- do.call(rbind,preds)

library(ROCR)
roc_pred <- prediction(stack$pct_male, stack$gender_true)
auc_rocr <- performance(roc_pred, measure="auc")
perf <- performance(roc_pred, measure="tpr", x.measure="fpr")
data.frame(FPR = perf@x.values[[1]], TPR = perf@y.values[[1]]) %>% ggplot(aes(x = FPR,y = TPR)) + geom_line() + theme_bw() + geom_abline(slope = 1, linetype = 3)
```






